<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowDown, ArrowUp, Check, ChevronLeft, Clock3, Copy, MoreHorizontal, Plus, Search, TimerReset, Trash2, X } from '@lucide/vue'
import { useAppStore, type WorkoutExercise, type WorkoutSet } from '@/stores/app'
const store=useAppStore();const router=useRouter();const tick=ref(Date.now());const showExercises=ref(false);const query=ref('');const pausedRest=ref(0);const interval=window.setInterval(()=>tick.value=Date.now(),1000);onBeforeUnmount(()=>clearInterval(interval))
const elapsed=computed(()=>{if(!store.activeWorkout)return'00:00';const seconds=Math.max(0,Math.floor((tick.value-new Date(store.activeWorkout.startedAt).getTime())/1000));return`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`});const rest=computed(()=>Math.max(0,Math.ceil(((store.restEndsAt??0)-tick.value)/1000)));const restLabel=computed(()=>`${String(Math.floor(rest.value/60)).padStart(2,'0')}:${String(rest.value%60).padStart(2,'0')}`);const available=computed(()=>store.exerciseList.filter(item=>!store.activeWorkout?.exercises.some(e=>e.exerciseId===item.id)&&item.name.toLowerCase().includes(query.value.toLowerCase())))
function copyPrevious(set:WorkoutSet){const[w,r]=set.previous.split('x').map(x=>Number(x.trim()));if(Number.isFinite(w))set.weight=w!;if(Number.isFinite(r))set.reps=r!}
async function complete(item:WorkoutExercise,set:WorkoutSet){if(!store.toggleSet(item,set))return alert('Check the weight, reps and RPE values.');if(set.done&&store.profile.timerAlerts&&'Notification'in window&&Notification.permission==='default')await Notification.requestPermission()}
function adjustTimer(seconds:number){if(pausedRest.value)pausedRest.value=Math.max(1,pausedRest.value+seconds);else store.restEndsAt=Math.max(Date.now()+1000,(store.restEndsAt||Date.now())+seconds*1000)}
function pauseTimer(){if(pausedRest.value){store.restEndsAt=Date.now()+pausedRest.value*1000;pausedRest.value=0}else{pausedRest.value=rest.value;store.restEndsAt=null}}
function skipTimer(){pausedRest.value=0;store.restEndsAt=null}
function finish(){if(!store.completedSets)return alert('Complete at least one set first.');if(store.completedSets<store.totalSets&&!confirm('Some sets are incomplete. Finish anyway?'))return;store.finishWorkout();router.push('/workout/summary')}
function discard(){if(confirm('Discard this workout? This cannot be undone.')){store.discardWorkout();router.push('/')}}
function add(itemId:string){const item=store.exerciseList.find(e=>e.id===itemId);if(item)store.addExercise(item);query.value=''}
watch(rest,(value,previous)=>{if(previous>0&&value===0&&store.profile.timerAlerts){navigator.vibrate?.([180,80,180]);if('Notification'in window&&Notification.permission==='granted')new Notification('Rest complete',{body:'Time for your next set.'})}})
</script>
<template>
  <div v-if="!store.activeWorkout" class="empty-state"><span class="empty-icon"><TimerReset :size="28"/></span><h1>No workout in progress</h1><p>Pick a routine or start an empty workout.</p><div class="empty-actions"><RouterLink to="/routines" class="btn btn-primary">Browse routines</RouterLink><button class="btn btn-quiet" @click="store.startEmpty()">Start empty</button></div></div>
  <div v-else class="workout-page"><header class="workout-top"><button class="icon-button" aria-label="Back" @click="router.push('/')"><ChevronLeft/></button><div><input v-model="store.activeWorkout.title" class="workout-title-input" maxlength="60"/><span><span class="live-dot"></span>{{ elapsed }}</span></div><button class="btn btn-finish" @click="finish">Finish</button></header><div class="workout-progress"><span :style="{width:`${store.totalSets?store.completedSets/store.totalSets*100:0}%`}"></span></div>
    <main class="workout-content"><label class="workout-note-field"><input v-model="store.activeWorkout.note" placeholder="Add a workout note" maxlength="240"/></label><section v-for="(item,itemIndex) in store.activeWorkout.exercises" :key="item.id" class="exercise-card"><header><div><span class="eyebrow">{{ store.exerciseList.find(x=>x.id===item.exerciseId)?.muscle||'EXERCISE' }}</span><h2>{{ item.name }}</h2></div><details class="action-menu exercise-actions"><summary class="icon-button"><MoreHorizontal :size="20"/></summary><div><button :disabled="itemIndex===0" @click="store.moveWorkoutExercise(item.id,-1)"><ArrowUp :size="15"/> Move up</button><button :disabled="itemIndex===store.activeWorkout.exercises.length-1" @click="store.moveWorkoutExercise(item.id,1)"><ArrowDown :size="15"/> Move down</button><button class="danger-text" @click="store.removeWorkoutExercise(item.id)"><Trash2 :size="15"/> Remove</button></div></details></header><div class="exercise-controls"><input v-model="item.note" placeholder="Exercise note"/><label>Rest<select v-model.number="item.rest"><option :value="60">1:00</option><option :value="90">1:30</option><option :value="120">2:00</option><option :value="180">3:00</option></select></label></div><div class="set-header"><span>SET</span><span>PREVIOUS</span><span>{{ store.profile.units.toUpperCase() }}</span><span>REPS</span><span>RPE</span><span></span></div>
      <div v-for="(set,index) in item.sets" :key="set.id" class="set-row" :class="{complete:set.done}"><details class="set-menu"><summary class="set-number" :title="set.type">{{ set.type==='Normal'?index+1:set.type[0] }}</summary><div><strong>{{ set.type }}</strong><button @click="store.cycleSetType(set)">Change type</button><button @click="store.duplicateSet(item,set.id)"><Copy :size="13"/> Duplicate</button><button :disabled="item.sets.length===1" class="danger-text" @click="store.removeSet(item,set.id)"><Trash2 :size="13"/> Delete</button></div></details><button class="previous" :aria-label="'Copy previous '+set.previous" @click="copyPrevious(set)">{{ set.previous }} <Copy :size="12"/></button><input v-model.number="set.weight" type="number" inputmode="decimal" min="0" step="0.5" :aria-label="`Weight in ${store.profile.units}`"/><input v-model.number="set.reps" type="number" inputmode="numeric" min="0" aria-label="Repetitions"/><input v-model.number="set.rpe" type="number" inputmode="decimal" min="1" max="10" step="0.5" placeholder="-" aria-label="RPE"/><button class="check-button" :aria-label="set.done?'Mark incomplete':'Complete set'" @click="complete(item,set)"><Check :size="19" stroke-width="3"/></button></div><button class="add-set" @click="store.addSet(item)"><Plus :size="16"/> Add set</button></section>
      <div v-if="!store.activeWorkout.exercises.length" class="inline-empty workout-empty"><strong>Your workout is empty</strong><span>Add an exercise to begin logging.</span></div><button class="add-exercise" @click="showExercises=true"><Plus :size="19"/> Add exercise</button><button class="cancel-workout" @click="router.push('/')">Save and close</button><button class="discard-workout" @click="discard">Discard workout</button></main>
    <div v-if="rest>0||pausedRest>0" class="rest-timer"><span><Clock3 :size="20"/><span><small>{{ pausedRest?'PAUSED':'REST TIMER' }}</small><strong>{{ pausedRest?`${String(Math.floor(pausedRest/60)).padStart(2,'0')}:${String(pausedRest%60).padStart(2,'0')}`:restLabel }}</strong></span></span><button @click="adjustTimer(-30)">-30s</button><button @click="pauseTimer">{{ pausedRest?'Resume':'Pause' }}</button><button @click="adjustTimer(30)">+30s</button><button aria-label="Skip timer" @click="skipTimer"><X :size="18"/></button></div>
    <div v-if="showExercises" class="sheet-backdrop" @click.self="showExercises=false"><section class="sheet"><header><div><span class="eyebrow">EXERCISE LIBRARY</span><h2>Add exercise</h2></div><button class="icon-button" @click="showExercises=false"><X/></button></header><div class="search-field compact"><Search :size="17"/><input v-model="query" placeholder="Search exercises" autofocus/></div><button v-for="exercise in available" :key="exercise.id" class="exercise-option" @click="add(exercise.id)"><span class="exercise-glyph">{{ exercise.name[0] }}</span><span><strong>{{ exercise.name }}</strong><small>{{ exercise.muscle }} - {{ exercise.equipment }}</small></span><Plus :size="19"/></button><p v-if="!available.length" class="small-empty">No more matching exercises.</p></section></div>
  </div>
</template>
