<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Plus, Search, Trash2, X } from '@lucide/vue'
import { useAppStore, type Exercise } from '@/stores/app'
const store=useAppStore();const query=ref('');const muscle=ref('All');const selected=ref<Exercise|null>(null);const dialog=ref<HTMLDialogElement>();const form=reactive({name:'',muscle:'Chest',equipment:'Barbell',instructions:''})
const muscles=computed(()=>['All',...new Set(store.exerciseList.map(x=>x.muscle))]);const filtered=computed(()=>store.exerciseList.filter(x=>(muscle.value==='All'||x.muscle===muscle.value)&&x.name.toLowerCase().includes(query.value.toLowerCase())))
function openCreate(){Object.assign(form,{name:'',muscle:'Chest',equipment:'Barbell',instructions:''});dialog.value?.showModal()}
function create(){if(!form.name.trim())return;const id=store.createCustomExercise({...form,name:form.name.trim()});dialog.value?.close();selected.value=store.exerciseList.find(x=>x.id===id)??null}
function remove(){if(selected.value?.custom&&confirm('Delete this custom exercise?')){store.deleteCustomExercise(selected.value.id);selected.value=null}}
</script>
<template><div class="page"><header class="page-head"><div><span class="eyebrow">MOVEMENT LIBRARY</span><h1>Exercises</h1><p>Find the right movement in seconds.</p></div><button class="btn btn-primary" @click="openCreate"><Plus :size="18"/> Custom exercise</button></header><div class="search-field"><Search :size="19"/><input v-model="query" placeholder="Search exercises" aria-label="Search exercises"/></div><div class="filter-chips"><button v-for="item in muscles" :key="item" :class="{active:muscle===item}" @click="muscle=item">{{ item }}</button></div><section class="exercise-browser"><div class="exercise-list"><button v-for="item in filtered" :key="item.id" :class="{selected:selected?.id===item.id}" @click="selected=item"><span class="exercise-glyph">{{ item.name[0] }}</span><span><strong>{{ item.name }}</strong><small>{{ item.muscle }} - {{ item.equipment }}</small></span><span class="chevron">›</span></button><p v-if="!filtered.length" class="small-empty">No exercises match your search.</p></div><aside v-if="selected" class="exercise-detail panel"><button class="icon-button close-detail" aria-label="Close details" @click="selected=null"><X :size="18"/></button><span class="exercise-glyph large">{{ selected.name[0] }}</span><span class="eyebrow">{{ selected.muscle }} - {{ selected.equipment }}</span><h2>{{ selected.name }}</h2><p>{{ selected.instructions }}</p><div class="detail-tags"><span>{{ selected.custom?'Custom':'Built-in' }}</span><span>{{ selected.equipment }}</span></div><button v-if="selected.custom" class="logout-button" @click="remove"><Trash2 :size="16"/> Delete custom exercise</button></aside></section><dialog ref="dialog" class="form-dialog"><form method="dialog" @submit.prevent="create"><header><div><span class="eyebrow">CUSTOM MOVEMENT</span><h2>Create exercise</h2></div><button type="button" class="icon-button" @click="dialog?.close()"><X/></button></header><label class="field-label">Name<input v-model="form.name" required maxlength="80" placeholder="Exercise name"/></label><div class="field-pair"><label class="field-label">Muscle<select v-model="form.muscle"><option v-for="item in muscles.filter(x=>x!=='All')" :key="item">{{ item }}</option></select></label><label class="field-label">Equipment<select v-model="form.equipment"><option>Barbell</option><option>Dumbbell</option><option>Cable</option><option>Machine</option><option>Bodyweight</option><option>Other</option></select></label></div><label class="field-label">Instructions<textarea v-model="form.instructions" rows="4" maxlength="500" placeholder="Setup and technique cues"></textarea></label><button class="btn btn-primary btn-wide" type="submit">Create exercise</button></form></dialog></div></template>
