<script setup lang="ts">
import { computed, ref } from 'vue'
import { CalendarDays, ChevronRight, Dumbbell, Search, X } from '@lucide/vue'
import { useAppStore, workoutDuration, workoutVolume, type Workout } from '@/stores/app'
const store=useAppStore();const showFilters=ref(false);const query=ref('');const from=ref('');const to=ref('')
const filtered=computed(()=>store.history.filter(workout=>workout.title.toLowerCase().includes(query.value.toLowerCase())&&(!from.value||workout.startedAt.slice(0,10)>=from.value)&&(!to.value||workout.startedAt.slice(0,10)<=to.value)))
const months=computed<Record<string,Workout[]>>(()=>filtered.value.reduce((groups,workout)=>{const month=new Date(workout.startedAt).toLocaleString('en',{month:'long',year:'numeric'});(groups[month]??=[]).push(workout);return groups},{} as Record<string,Workout[]>))
function clear(){query.value='';from.value='';to.value=''}
</script>
<template><div class="page"><header class="page-head"><div><span class="eyebrow">EVERY REP COUNTS</span><h1>History</h1><p>Your complete training record.</p></div><button class="btn btn-quiet" @click="showFilters=!showFilters"><CalendarDays :size="18"/> Filter</button></header><section v-if="showFilters" class="filter-bar"><label><Search :size="16"/><input v-model="query" placeholder="Routine or workout"/></label><label>From<input v-model="from" type="date"/></label><label>To<input v-model="to" type="date"/></label><button class="icon-button" aria-label="Clear filters" @click="clear"><X :size="17"/></button></section><section v-for="(workouts,month) in months" :key="month" class="history-month"><div class="folder-head"><span>{{ month }}</span><small>{{ workouts.length }} workouts</small></div><RouterLink v-for="workout in workouts" :key="workout.id" :to="`/history/${workout.id}`" class="history-card history-summary"><span class="date-tile"><strong>{{ new Date(workout.startedAt).getDate() }}</strong><small>{{ new Date(workout.startedAt).toLocaleString('en',{weekday:'short'}) }}</small></span><span><strong>{{ workout.title }}</strong><small>{{ workoutDuration(workout) }} min - {{ Math.round(workoutVolume(workout)).toLocaleString() }} {{ store.profile.units }} - {{ workout.exercises.flatMap(e=>e.sets).filter(s=>s.done).length }} sets</small></span><ChevronRight :size="19"/></RouterLink></section><div v-if="!filtered.length" class="empty-state compact-empty"><Dumbbell :size="30"/><h2>No workouts found</h2><p>Try changing your filters or finish a new session.</p><button v-if="query||from||to" class="btn btn-quiet" @click="clear">Clear filters</button></div></div></template>
