<script setup lang="ts">
import { useRouter } from 'vue-router'
import { Copy, Pencil, Play, Plus, Trash2 } from '@lucide/vue'
import { routineSubtitle, useAppStore } from '@/stores/app'
const store=useAppStore();const router=useRouter()
function start(id:string){store.startRoutine(id);router.push('/workout')}
function remove(id:string){if(confirm('Delete this routine? Your workout history will stay intact.'))store.deleteRoutine(id)}
</script>
<template><div class="page"><header class="page-head"><div><span class="eyebrow">TRAIN YOUR WAY</span><h1>Routines</h1><p>Repeatable plans for focused sessions.</p></div><RouterLink to="/routines/new" class="btn btn-primary"><Plus :size="18"/> New routine</RouterLink></header><div class="folder-head"><span>MY ROUTINES</span><small>{{ store.routineList.length }} routines</small></div><section class="routine-grid"><article v-for="routine in store.routineList" :key="routine.id" class="routine-card"><header><span class="routine-monogram">{{ routine.name.split(' ').map(x=>x[0]).join('').slice(0,2) }}</span><RouterLink :to="`/routines/${routine.id}/edit`" class="icon-button" :aria-label="'Edit '+routine.name"><Pencil :size="18"/></RouterLink></header><div><h2>{{ routine.name }}</h2><p>{{ routineSubtitle(routine) }}</p><small class="routine-description">{{ routine.description }}</small><ul><li v-for="item in routine.exercises.slice(0,4)" :key="item.id">{{ item.name }}</li></ul></div><footer><details class="action-menu"><summary class="btn btn-quiet">More</summary><div><button @click="store.duplicateRoutine(routine.id)"><Copy :size="15"/> Duplicate</button><button class="danger-text" @click="remove(routine.id)"><Trash2 :size="15"/> Delete</button></div></details><button class="btn btn-primary" @click="start(routine.id)"><Play :size="16" fill="currentColor"/> {{ store.activeWorkout ? 'Resume' : 'Start' }}</button></footer></article><RouterLink to="/routines/new" class="routine-card add-routine-card"><Plus :size="26"/><strong>Create a routine</strong><span>Build your next training session.</span></RouterLink></section></div></template>
